project_id = "ofbypucaiibkpnfwzrlo"

[functions.fetch-binance-whales]
verify_jwt = true
regions = ["southeast-asia"]

[functions.fetch-binance-spot]
verify_jwt = true

[functions.fetch-binance-margin]
verify_jwt = true