project_id = "ofbypucaiibkpnfwzrlo"

[api]
enabled = true
# Restrict the regions that your edge function can be invoked from
regions = ["southeast-asia"] # This will make the function run in Singapore

[functions]
[functions.fetch-binance-whales]
verify_jwt = true