name = "ai-trend-sentinel"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "bun run build"

[site]
bucket = "./dist"

[build.upload]
format = "service-worker"

pages_build_output_dir = "dist"